name: rules

on:
  workflow_dispatch:
  push:
    branches:
      - rules

jobs:
  upload_to_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: rules

      - name: Get latest release tag
        id: get_release
        run: |
          TAG_NAME=$(curl --silent https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "Latest release tag: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Upload files to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: false
          file: geosite.dat
          release_name: Updated Release
          tag: ${{ env.TAG_NAME }}
